AllCops:
  Exclude:
    - 'dotenv-android.gemspec'
    - 'vendor/**/*'
    - 'Dangerfile'

Metrics/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 40

Documentation:
  Enabled: false