name: Deploy next version 
on: 
  push:    
    branches: ['main', 'beta', 'alpha']

jobs:
  deploy:
    name: Create tag, deploy binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Deploy git tag and Gradle plugin release via Semantic Release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 17
          extra_plugins: |
            @semantic-release/commit-analyzer@8
            @semantic-release/release-notes-generator@9
            @semantic-release/changelog@5
            @semantic-release/git@9
            @semantic-release/github@7
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}